services:
  postgres:
    image: postgres:14
    container_name: loan_postgres
    environment:
      POSTGRES_DB: loans
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    networks:
      - loan-network

  springboot-app:
    build: .
    container_name: loan_springboot
    depends_on:
      - postgres
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loans
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - loan-network

networks:
  loan-network:
