# Exported from Render on 2025-07-10T13:16:04Z
services:
- type: web
  name: Loan-Management-System-1
  runtime: docker
  repo: https://github.com/Dhivya631/Loan-Management-System
  plan: free
  envVars:
  - key: DB_NAME
    sync: false
  - key: DB_PORT
    sync: false
  - key: DB_HOST
    sync: false
  - key: SSL_PASSWORD
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: DB_URL
    sync: false
  - key: DB_PASSWORD
    sync: false
  - key: DB_USERNAME
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
