name: Java CI with Maven and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-docker-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 18
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t loan-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag loan-app:latest ${{ secrets.DOCKER_USERNAME }}/loanmanagement:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/loanmanagement:latest

      - name: Step 1 - Pull Docker image
        run: docker pull dhivyard/loanmanagement:latest

      - name: Step 2 - Run PostgreSQL container
        run: |
          docker run -d --name my-postgres \
            -e POSTGRES_USER=${{ secrets.DB_USERNAME }} \
            -e POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e POSTGRES_DB=loans \
            -p 5432:5432 postgres

      - name: Step 3 - Run Loan Management container
        run: |
          docker run -d --name loan \
            --link my-postgres:postgres \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/loans \
            -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -p 8083:8083 dhivyard/loanmanagement:latest

      - name: Step 4 - Show Loan App Logs
        run: |
          CONTAINER_ID=$(docker ps -qf "name=loan")
          docker logs $CONTAINER_ID
